INSERT INTO system_announcement (title, content, type, target, publish_time, end_time, status) VALUES 
('系统维护通知', '尊敬的用户，为了提供更好的服务，我们将于本周六凌晨2:00-6:00进行系统维护。维护期间系统将暂时无法使用，请提前做好准备。给您带来不便，敬请谅解！', '通知', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 1),
('新功能上线公告', '系统新增健康数据分析功能！现在您可以查看个人健康数据的趋势分析图表，包括血压、血糖、心率等指标的变化趋势。快来体验吧！', '公告', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 1),
('安全提醒', '近期发现有不法分子尝试通过钓鱼邮件获取用户信息，请大家注意识别，不要点击不明链接，不要泄露个人账号信息。', '警告', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 14 DAY), 1),
('使用指南更新', '我们更新了系统使用指南，新增了智能提醒设置、家庭成员管理等功能的详细说明。请点击帮助中心查看最新版本。', '通知', '新用户', NOW(), DATE_ADD(NOW(), INTERVAL 60 DAY), 1),
('VIP服务升级', 'VIP会员用户现在可以享受专属的健康顾问服务，7x24小时在线咨询，个性化健康方案定制等特权。', '公告', 'VIP用户', NOW(), DATE_ADD(NOW(), INTERVAL 90 DAY), 0),
('数据迁移通知', '为了提升系统性能，我们将在下周进行数据迁移工作。迁移过程中可能会出现短暂的数据延迟，这是正常现象，请放心使用。', '通知', '全体用户', DATE_ADD(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 8 DAY), 1),
('移动端APP发布', '我们的移动端APP已经正式发布！支持iOS和Android平台，您可以在App Store或应用商店搜索"健康管家"下载安装。', '公告', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 45 DAY), 1),
('隐私政策更新', '根据最新的隐私保护法规，我们更新了隐私政策。请您仔细阅读并确认同意。', '通知', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 1),
('服务器扩容通知', '由于用户数量持续增长，我们将于下周二进行服务器扩容升级。升级期间系统可能会有短暂的性能波动，请您谅解。', '通知', '全体用户', DATE_ADD(NOW(), INTERVAL 2 DAY), DATE_ADD(NOW(), INTERVAL 9 DAY), 1),
('健康讲座预告', '本周六下午3点，我们将举办一场关于健康饮食的线上讲座，欢迎各位用户参加！', '公告', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 1),
('系统性能优化完成', '经过一周的努力，系统性能优化工作已完成。现在系统响应速度提升了30%，祝您使用愉快！', '通知', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 1),
('常见问题解答更新', '我们更新了常见问题解答页面，新增了关于数据导出、账号安全等方面的问题解答。', '通知', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 60 DAY), 1),
('会员日活动', '每月8号是我们的会员日，会员用户可以享受专属优惠和福利！', '公告', 'VIP用户', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 1),
('紧急安全公告', '发现系统存在安全漏洞，已紧急修复。请所有用户及时更新密码，确保账号安全。', '警告', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 7 DAY), 1),
('新功能内测招募', '我们即将推出全新的智能健康助手功能，现招募100名内测用户，感兴趣的用户请联系客服报名。', '公告', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 14 DAY), 1),
('客服时间调整', '自下周一起，客服工作时间调整为9:00-21:00，为您提供更长时间的服务支持。', '通知', '全体用户', DATE_ADD(NOW(), INTERVAL 1 DAY), DATE_ADD(NOW(), INTERVAL 30 DAY), 1),
('数据备份通知', '为确保数据安全，我们将每周日凌晨进行全量数据备份。备份期间系统可能会有短暂不可用，请提前做好准备。', '通知', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 60 DAY), 1),
('健康报告分享功能上线', '现在您可以将您的健康报告分享给家人和朋友了！点击报告详情页的分享按钮即可。', '公告', '全体用户', NOW(), DATE_ADD(NOW(), INTERVAL 45 DAY), 1),
('积分商城更新', '积分商城新增了多款健康礼品，包括智能手环、健康体检套餐等，快来兑换吧！', '公告', 'VIP用户', NOW(), DATE_ADD(NOW(), INTERVAL 30 DAY), 1),
('系统升级公告', '系统将于下周三进行重大版本升级，新增AI健康顾问、智能用药提醒等多项功能，敬请期待！', '公告', '全体用户', DATE_ADD(NOW(), INTERVAL 3 DAY), DATE_ADD(NOW(), INTERVAL 10 DAY), 1);

INSERT INTO api_config (api_name, api_type, endpoint, app_key, app_secret, status, remarks) VALUES 
('百度OCR文字识别', 'AI咨询', 'https://aip.baidubce.com/rest/2.0/ocr/v1/general_basic', 'test-ocr-key', 'test-ocr-secret', 1, '用于识别医疗单据上的文字信息'),
('百度文心一言API', 'AI咨询', 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions', 'test-ernie-key', 'test-ernie-secret', 1, '用于智能问答和健康咨询'),
('健康风险评估引擎', '健康评估', 'https://api.example.com/v1/health/assessment', 'test-assess-key', 'test-assess-secret', 1, '基于用户健康数据进行风险评估'),
('智能用药推荐', '智能推荐', 'https://api.example.com/v1/medicine/recommend', 'test-medicine-key', 'test-medicine-secret', 1, '根据用户病情推荐合适药物'),
('体检报告分析', '健康评估', 'https://api.example.com/v1/report/analysis', 'test-report-key', 'test-report-secret', 0, '分析体检报告数据，生成健康建议'),
('营养膳食建议', '智能推荐', 'https://api.example.com/v1/nutrition/suggest', 'test-nutrition-key', 'test-nutrition-secret', 1, '根据用户身体状况提供膳食建议'),
('疾病预测模型', '健康评估', 'https://api.example.com/v1/disease/predict', 'test-disease-key', 'test-disease-secret', 0, '基于机器学习模型预测疾病风险'),
('运动计划推荐', '智能推荐', 'https://api.example.com/v1/exercise/plan', 'test-exercise-key', 'test-exercise-secret', 1, '根据用户健康数据制定运动计划'),
('语音识别API', 'AI咨询', 'https://api.example.com/v1/speech/recognize', 'test-speech-key', 'test-speech-secret', 1, '用于语音转文字功能'),
('图像识别API', 'AI咨询', 'https://api.example.com/v1/image/recognize', 'test-image-key', 'test-image-secret', 1, '用于医疗影像分析'),
('健康数据预测', '健康评估', 'https://api.example.com/v1/health/predict', 'test-predict-key', 'test-predict-secret', 1, '预测用户健康趋势'),
('个性化健康方案', '智能推荐', 'https://api.example.com/v1/health/plan', 'test-plan-key', 'test-plan-secret', 1, '为用户定制个性化健康方案'),
('药品信息查询', 'AI咨询', 'https://api.example.com/v1/drug/info', 'test-drug-key', 'test-drug-secret', 1, '查询药品详细信息'),
('症状自查API', '健康评估', 'https://api.example.com/v1/symptom/check', 'test-symptom-key', 'test-symptom-secret', 1, '用户症状自我检查'),
('健康知识推荐', '智能推荐', 'https://api.example.com/v1/knowledge/recommend', 'test-knowledge-key', 'test-knowledge-secret', 1, '根据用户兴趣推荐健康知识'),
('情绪分析API', '健康评估', 'https://api.example.com/v1/emotion/analyze', 'test-emotion-key', 'test-emotion-secret', 0, '分析用户情绪状态'),
('睡眠质量分析', '健康评估', 'https://api.example.com/v1/sleep/analyze', 'test-sleep-key', 'test-sleep-secret', 1, '分析用户睡眠数据'),
('心率变异性分析', '健康评估', 'https://api.example.com/v1/heart/variability', 'test-heart-key', 'test-heart-secret', 1, '分析心率变异性指标'),
('智能问答机器人', 'AI咨询', 'https://api.example.com/v1/chat/robot', 'test-chat-key', 'test-chat-secret', 1, '智能客服问答系统'),
('健康数据可视化', 'AI咨询', 'https://api.example.com/v1/visualization/health', 'test-visual-key', 'test-visual-secret', 1, '健康数据图表可视化');